"use client"

import { useState } from "react"
import Image from "next/image"
import { Droplets, Shield, Sparkles, Waves } from "lucide-react"

interface ProductScannerOverlayProps {
  imageUrl: string
  scanMode: "all" | "humectant" | "moisturizer" | "emollient" | "occlusive"
  onProductSelect: (product: any) => void
}

interface ProductMarker {
  id: number
  x: number
  y: number
  width: number
  height: number
  type: "humectant" | "moisturizer" | "emollient" | "occlusive"
  name: string
}

export function ProductScannerOverlay({ imageUrl, scanMode, onProductSelect }: ProductScannerOverlayProps) {
  // Sample product markers - in a real app, these would be generated by image recognition
  const [productMarkers] = useState<ProductMarker[]>([
    // Top shelf - CeraVe products (mostly moisturizers)
    { id: 1, x: 10, y: 10, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },
    { id: 2, x: 80, y: 10, width: 60, height: 80, type: "moisturizer", name: "CeraVe Daily Moisturizing Lotion" },
    { id: 3, x: 150, y: 10, width: 60, height: 80, type: "moisturizer", name: "CeraVe AM Facial Moisturizer" },
    { id: 4, x: 220, y: 10, width: 60, height: 80, type: "moisturizer", name: "CeraVe PM Facial Moisturizer" },
    { id: 5, x: 290, y: 10, width: 60, height: 80, type: "occlusive", name: "CeraVe Healing Ointment" },

    // Middle shelf - CeraVe products (mix of types)
    { id: 6, x: 10, y: 110, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },
    { id: 7, x: 80, y: 110, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },
    { id: 8, x: 150, y: 110, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },
    { id: 9, x: 220, y: 110, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },
    { id: 10, x: 290, y: 110, width: 60, height: 80, type: "moisturizer", name: "CeraVe Moisturizing Cream" },

    // Bottom shelves - Nivea products (mix of types)
    { id: 11, x: 10, y: 210, width: 60, height: 60, type: "emollient", name: "Nivea Soft Moisturizing Cream" },
    { id: 12, x: 80, y: 210, width: 60, height: 60, type: "emollient", name: "Nivea Soft Moisturizing Cream" },
    { id: 13, x: 150, y: 210, width: 60, height: 60, type: "humectant", name: "Nivea Hydrating Serum" },
    { id: 14, x: 220, y: 210, width: 60, height: 60, type: "humectant", name: "Nivea Hydrating Serum" },
    { id: 15, x: 290, y: 210, width: 60, height: 60, type: "occlusive", name: "Nivea Creme" },

    // Bottom shelf
    { id: 16, x: 10, y: 280, width: 60, height: 60, type: "humectant", name: "Nivea Hydrating Gel" },
    { id: 17, x: 80, y: 280, width: 60, height: 60, type: "humectant", name: "Nivea Hydrating Gel" },
    { id: 18, x: 150, y: 280, width: 60, height: 60, type: "emollient", name: "Nivea Body Lotion" },
    { id: 19, x: 220, y: 280, width: 60, height: 60, type: "emollient", name: "Nivea Body Lotion" },
    { id: 20, x: 290, y: 280, width: 60, height: 60, type: "emollient", name: "Nivea Body Lotion" },
  ])

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "humectant":
        return <Droplets className="h-3 w-3" />
      case "moisturizer":
        return <Waves className="h-3 w-3" />
      case "emollient":
        return <Sparkles className="h-3 w-3" />
      case "occlusive":
        return <Shield className="h-3 w-3" />
      default:
        return null
    }
  }

  const getTypeColor = (type: string) => {
    switch (type) {
      case "humectant":
        return "bg-sky-500/30 border-sky-500"
      case "moisturizer":
        return "bg-emerald-500/30 border-emerald-500"
      case "emollient":
        return "bg-amber-500/30 border-amber-500"
      case "occlusive":
        return "bg-purple-500/30 border-purple-500"
      default:
        return ""
    }
  }

  const getTypeTextColor = (type: string) => {
    switch (type) {
      case "humectant":
        return "bg-sky-100 text-sky-800"
      case "moisturizer":
        return "bg-emerald-100 text-emerald-800"
      case "emollient":
        return "bg-amber-100 text-amber-800"
      case "occlusive":
        return "bg-purple-100 text-purple-800"
      default:
        return ""
    }
  }

  const filteredMarkers =
    scanMode === "all" ? productMarkers : productMarkers.filter((marker) => marker.type === scanMode)

  return (
    <div className="relative w-full h-full">
      <Image src={imageUrl || "/placeholder.svg"} alt="Product shelf" fill className="object-cover" />

      {/* Product markers */}
      {filteredMarkers.map((marker) => (
        <div
          key={marker.id}
          className={`absolute border-2 ${getTypeColor(marker.type)} rounded-md cursor-pointer transition-all hover:border-white hover:scale-105`}
          style={{
            left: `${marker.x}px`,
            top: `${marker.y}px`,
            width: `${marker.width}px`,
            height: `${marker.height}px`,
          }}
          onClick={() =>
            onProductSelect({
              name: marker.name,
              type: marker.type.charAt(0).toUpperCase() + marker.type.slice(1),
              effectiveness: 75 + Math.floor(Math.random() * 20),
              description: "Rich, moisturizing cream for dry to very dry skin",
              ingredients: ["Ceramides", "Hyaluronic Acid", "Glycerin", "Petrolatum"],
            })
          }
        >
          <div
            className={`absolute -top-6 left-0 px-1.5 py-0.5 rounded text-xs flex items-center gap-1 whitespace-nowrap ${getTypeTextColor(marker.type)}`}
          >
            {getTypeIcon(marker.type)}
            {marker.type.charAt(0).toUpperCase() + marker.type.slice(1)}
          </div>
        </div>
      ))}
    </div>
  )
}
